import { User, Job, Application, Interview, Report } from "../models/index.js";
import { ApiError } from "../utils/ApiError.js";
import { ROLES, APPLICATION_STATUS } from "../constants/index.js";
import { renderPdfToBuffer, sectionHeading } from "../utils/pdfBuilder.js";

function periodFor(type, customStart, customEnd) {
  const now = new Date();
  if (type === "custom") {
    if (!customStart || !customEnd)
      throw ApiError.badRequest(
        "Custom reports require periodStart and periodEnd",
      );
    return { start: new Date(customStart), end: new Date(customEnd) };
  }
  const start = new Date(now);
  if (type === "daily") start.setDate(start.getDate() - 1);
  else if (type === "weekly") start.setDate(start.getDate() - 7);
  else start.setMonth(start.getMonth() - 1);
  return { start, end: now };
}

function labelFor(type, start, end) {
  const fmt = (d) =>
    d.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  if (type === "daily") return "Daily summary";
  if (type === "weekly") return `Weekly summary — ${fmt(start)} to ${fmt(end)}`;
  if (type === "monthly")
    return `Monthly report — ${fmt(start)} to ${fmt(end)}`;
  return `Custom report — ${fmt(start)} to ${fmt(end)}`;
}

export const reportService = {
  async generate(adminId, { type, periodStart, periodEnd }) {
    const { start, end } = periodFor(type, periodStart, periodEnd);
    const range = { createdAt: { $gte: start, $lte: end } };

    const [
      newUsers,
      newStudents,
      newRecruiters,
      newJobs,
      newApplications,
      interviewsScheduled,
      hires,
    ] = await Promise.all([
      User.countDocuments(range),
      User.countDocuments({ ...range, role: ROLES.STUDENT }),
      User.countDocuments({ ...range, role: ROLES.RECRUITER }),
      Job.countDocuments(range),
      Application.countDocuments(range),
      Interview.countDocuments(range),
      Application.countDocuments({
        ...range,
        status: APPLICATION_STATUS.OFFERED,
      }),
    ]);

    const report = await Report.create({
      name: labelFor(type, start, end),
      type,
      periodStart: start,
      periodEnd: end,
      generatedBy: adminId,
      data: {
        newUsers,
        newStudents,
        newRecruiters,
        newJobs,
        newApplications,
        interviewsScheduled,
        hires,
      },
    });

    return report;
  },

  async list() {
    return Report.find()
      .populate("generatedBy", "name email")
      .sort({ createdAt: -1 })
      .limit(50);
  },

  async getById(id) {
    const report = await Report.findById(id).populate(
      "generatedBy",
      "name email",
    );
    if (!report) throw ApiError.notFound("Report not found");
    return report;
  },

  async toCsv(reportId) {
    const report = await this.getById(reportId);
    const rows = [
      ["Metric", "Value"],
      ["Report", report.name],
      ["Period start", report.periodStart.toISOString()],
      ["Period end", report.periodEnd.toISOString()],
      ["New users", report.data.newUsers],
      ["New students", report.data.newStudents],
      ["New recruiters", report.data.newRecruiters],
      ["New jobs posted", report.data.newJobs],
      ["New applications", report.data.newApplications],
      ["Interviews scheduled", report.data.interviewsScheduled],
      ["Hires (offers made)", report.data.hires],
    ];
    return rows
      .map((r) =>
        r.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","),
      )
      .join("\n");
  },

  async toPdf(reportId) {
    const report = await this.getById(reportId);
    return renderPdfToBuffer((doc) => {
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .fillColor("#0F172A")
        .text("CareerNexus");
      doc.fontSize(11).font("Helvetica").fillColor("#64748B").text(report.name);
      doc.moveDown(0.3);
      doc
        .fontSize(9)
        .fillColor("#94A3B8")
        .text(
          `${report.periodStart.toDateString()} — ${report.periodEnd.toDateString()}   ·   Generated by ${report.generatedBy?.name || "Admin"}`,
        );

      sectionHeading(doc, "Platform metrics");
      const rows = [
        ["New users", report.data.newUsers],
        ["New students", report.data.newStudents],
        ["New recruiters", report.data.newRecruiters],
        ["New jobs posted", report.data.newJobs],
        ["New applications", report.data.newApplications],
        ["Interviews scheduled", report.data.interviewsScheduled],
        ["Hires (offers made)", report.data.hires],
      ];
      rows.forEach(([label, value]) => {
        doc
          .fontSize(10.5)
          .font("Helvetica")
          .fillColor("#1E293B")
          .text(label, { continued: true, width: 300 });
        doc.font("Helvetica-Bold").text(`  ${value}`);
      });
    });
  },
};
